config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles #gave a lot of paths for CRUD for the table in db, can check with rails routes

  get 'signup', to: 'users#new' #users controller, 'new' action
  resources :users, except: [:new] #want all the routes except new user route, because already got signup

  resources :categories, exception: [:destroy] # do not allow destroy for categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  #getters and setters will be given by rails, can be filled by console since table is already in schema
  validates :title, presence: true, length: {minimum: 3, maximum: 50} #ensure that there is a title before saving
  validates :description, presence: true, length: {minimum: 3, maximum: 50}
  validates :user_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name #ensure name is unique, has default case_sensitive = true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 } #ensure username is present
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX } #check validity of email format
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy] #before these actions do anything, access method set_article

  def index
    @articles = Article.all
  end

  def new #action
  @article = Article.new #will be passed to the view page
  end

  def edit
  end

  def create #action, handles form submission from new page
    #render plain: params[:article].inspect #show what happens
    @article = Article.new(article_params) #need to create new article from the params passed in, uses a method
    @article.user = User.first

    if @article.save
      flash[:notice] = "Article was successfully created." #only for one cycle
      redirect_to article_path(@article)
    else #if article does not pass the validations of save
    render 'new' #show the new template again
    end

  end

  def update #action that handles form from edit page
    if @article.update(article_params) #params is an instance of Parameter in controller; looks like a hash
      flash[:notice] = "Article was successfully edited"
      redirect_to article_path(@article) #redirecting to 'show' page
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
  end

  private
    def set_article
      @article = Article.find(params[:id]) # param in url
    end

    #this validation is for form inputs
    def article_params #to whitelist values being passed, from params, will allow these attributes
      params.require(:article).permit(:title, :description) #article is the key, title and description are values
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def show
  end

  private #only available to this controller
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the alpha blog #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username,:email,:password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h1> Edit existing article </h1>

<% if @article.errors.any? %>
<h2>The following errors prevented the article from getting created </h2>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @article do |f| %> <!-- will auto fill based on controller logic; find article of param id -->
  <p>
    <%= f.label :title %> <br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %> <br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to "Back to articles listing", articles_path %>

app/views/articles/index.html.erb
<h1> Listing all articles </h1>
<p>
  <%= link_to "Create new article", new_article_path %>
</p>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>

  <% @articles.each do |a| %>
  <tr>
    <td><%= a.title %></td>
    <td><%= a.description %></td>
    <td>Created by: <%= a.user.username if a.user %>, <br> <%= time_ago_in_words(a.created_at) %> ago, <br>
    Last updated: <%= time_ago_in_words(a.updated_at) %></td>
    <td><%= link_to "Edit", edit_article_path(a) %></td>
    <td><%= link_to "Show", article_path(a) %></td>
    <tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>Create an article </h1>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %> <br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %> <br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/show.html.erb
<h1> Showing selected article </h1>

<p>
  Title: <%= @article.title %>
</p>

<p>
  Description: <%= @article.description  %>
</p>

<%= link_to "Edit this article", edit_article_path %> | 
<%= link_to "Back to articles listing", articles_path(@article) %>

app/views/categories/index.html.erb
<h1 align="center"> Listing all categories</h1>
<% @categories.each do |category| %>
  <div align="center"><ul class>
    <li>
      <%= link_to "#{category.name}", category_path(category) %>
    </li>
  </ul>
</div>
  <% end %>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<% if @category.errors.any? %>
<h2>The following errors prevented the category from getting created </h2>
<div><ul>
  <% @category.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul></div>
<% end %>

<%= form_for @category do |u| %>
  <p>
    <%= u.label :name %> <br />
    <%= u.text_field :name %>
  </p>
  <p>
    <%= u.submit %>
  </p>

<% end %>

<%= link_to "Back to articles listing", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% flash.each do |name, msg| %>
      <ul>
        <li> <%= msg %> </li>
      </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<body>
<h1>About me | <%= link_to 'Home',  root_path %></h1>

<%= image_tag 'tattoo.jpg', alt: '' %>



</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<body>
<h1>Welcome to my blog!</h1>

<p>You can find out more about me here: </p>
<%= link_to 'About Me',  about_path %>

</body>
</html>

app/views/users/new.html.erb
<h1>User Signup </h1>

<% if @user.errors.any? %>
<h2>The following errors prevented the article from getting created </h2>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @user do |u| %>
  <p>
    <%= u.label :username %> <br />
    <%= u.text_field :username %>
  </p>
  <p>
    <%= u.label :password %> <br />
    <%= u.password_field :password %>
  </p>
  <p>
    <%= u.label :email %> <br />
    <%= u.email_field :email %>
  </p>
  <p>
    <%= u.submit %>
  </p>

<% end %>

<%= link_to "Back to articles listing", articles_path %>